apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  labels:
    app: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: ticket-service:TAG_PLACEHOLDER
          ports:
            - containerPort: 8083
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ticket-secrets
                  key: SECRET_KEY
            - name: TICKET_QR_SECRET
              valueFrom:
                secretKeyRef:
                  name: ticket-secrets
                  key: TICKET_QR_SECRET
            - name: YOUR_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ticket-secrets
                  key: YOUR_APP_PASSWORD
          imagePullPolicy: IfNotPresent
