version: "3.8"
services:
  mongo-db:
    image: "mongo:latest"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: notificationDB # mongo can create a database without mentioning it here when our app interacts with it
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
  rabbit_broker:
    image: rabbitmq:3-management
    container_name: rabbitmq_SOA_NotifService
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_mq_SOA:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: transport
      RABBITMQ_DEFAULT_PASS: transport
volumes:
  mongo_data:
  redis_data:
  rabbit_mq_SOA: