apiVersion: v1
kind: Service
metadata:
  name: geolocation-service
  labels:
    app: geolocation-service
spec:
  selector:
    app: geolocation-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
