apiVersion: v1
kind: Service
metadata:
  name: authentication-db
spec:
  selector:
    app: authentication-db
  ports:
    - port: 5437
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: subscription-db
spec:
  selector:
    app: subscription-db
  ports:
    - port: 5439
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: ticket-db
spec:
  selector:
    app: ticket-db
  ports:
    - port: 5435
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: trip-db
spec:
  selector:
    app: trip-db
  ports:
    - port: 5438
      targetPort: 5432
