version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8090:8080"
      - "50000:50000"
    user: root
    volumes:
      - jenkins_home1:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - $HOME/.kube:/root/.kube
      - $HOME/.minikube:$HOME/.minikube  # Mount the entire .minikube directory
      - /usr/local/bin/kubectl:/usr/local/bin/kubectl
    environment:
      KUBECONFIG: /root/.kube/config
    networks:
      - minikube

volumes:
  jenkins_home1:

networks:
  minikube:
    external: true
    name: minikube